name: euterpe
description: A beautiful audio recorder.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  device_info_plus: ^2.0.1
  easy_localization: ^3.0.0
  equatable: ^2.0.3
  flare_flutter: ^3.0.1
  flutter_bloc: ^7.0.1
  hydrated_bloc: ^7.0.1
  just_audio: ^0.8.0
  package_info_plus: ^1.0.3
  path: ^1.8.0
  path_provider: ^2.0.2
  permission_handler: ^8.1.1
  shared_preferences: ^2.0.6
  sorted_list: ^1.0.0
  watcher: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/sounds/
    - assets/strings/

  fonts:
    - family: MontserratAlternates
      fonts:
        - asset: fonts/MontserratAlternates-Regular.ttf
          weight: 400
        - asset: fonts/MontserratAlternates-Medium.ttf
          weight: 500
        - asset: fonts/MontserratAlternates-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/ic_launcher.png"
  adaptive_icon_foreground: "assets/ic_launcher_foreground.png"
  adaptive_icon_background: "#FFFFFF"
